##### Fake vip #####
[MITM]
hostname = bmall.camera360.com, vsco.co, viva-asia1.vvbrd.com, api.picsart.com, owa.videoshowiosglobalserver.com:0, api-intl.mr.meitu.com, *.videostarapp.com, lcs-mobile-cops.adobe.io, 

[Script]
##########
# Anh & Video
# camera360
http-response ^https:\/\/bmall\.camera360\.com\/api\/(iap\/check-receipt$|mix\/getinfo$) requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/camera360.vip.js,script-update-interval=0
# vsco
http-response ^https?:\/\/vsco\.co\/api\/subscriptions\/2.1\/user-subscriptions\/ requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/vsco.js,script-update-interval=0
# Vivavideo
http-response ^https:\/\/viva-asia1\.vvbrd\.com\/api\/rest\/u\/vip requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/vivavideo.vip.js,script-update-interval=0
# PicsArt
http-response ^https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/picsArt.vip.js,script-update-interval=0
# Videoshow
http-response ^https:\/\/owa\.videoshowiosglobalserver\.com\/zone\/.+\/iosPayClient\/(payVerify|imeiVerify) requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/videoshow.vip.js,script-update-interval=0
# beautyplus
http-response ^https:\/\/api-intl\.mr\.meitu\.com/.*/subs_offer_elg$ requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/langkhach270389/Scripting/master/beautyplusvip.js,script-update-interval=0
# VideoStar
http-response ^https?:\/\/.*\.videostarapp\.com\/scripts\/subsNew\.php requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/script/master/VideoStar.js,script-update-interval=0
# phothop & PSexpress
http-response ^https:\/\/lcs-mobile-cops\.adobe\.io\/mobile_profile requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/langkhach270389/Scripting/master/photoshop.js,script-update-interval=0
##########
