##### Fake vip #####
[MITM]
hostname = photos.adobe.io, license.pdfexpert.com, api.lingokids.com, duolingo-leaderboards-prod.duolingo.com, receipt-validator.herewetest.com, license.pdfexpert.com, ssl-api.itranslateapp.com, education.github.com, ap*.intsig.net, secure.istreamer.com, subscription.grammarly.com, 

[Script]
##########
# Doccument
# lightroom
http-response ^https:\/\/photos\.adobe\.io\/v2\/accounts requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/Lightroom.js,script-update-interval=0
# Pdfexpert
http-response ^https:\/\/license\.pdfexpert\.com\/api\/1\.0\/pdfexpert6\/subscription\/(refresh$|check$) requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/Pdfexpert.vip.js,script-update-interval=0
# lingokids
http-response ^https:\/\/api\.lingokids\.com\/v1\/renovate_session$ requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/lingokids.vip.js,script-update-interval=0
# duolingo
http-response ^https:\/\/duolingo-leaderboards-prod\.duolingo\.com\/leaderboards* requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/duolingo.js,script-update-interval=0
# speak & translate
http-response ^https:\/\/receipt-validator\.herewetest\.com\/apple\/verifyTransaction$ requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/speak&translate.js,script-update-interval=0
# document
http-response ^https:\/\/license\.pdfexpert\.com\/api\/.+\/subscription\/(refresh$|check$) requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/Pdfexpert.vip.js,script-update-interval=0
# itranslate
http-response ^https:\/\/ssl-api\.itranslateapp\.com\/.*\/subscriptions\/.*\/ios$ requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/itranslate.js,script-update-interval=0
# workingcopy
http-response ^https:\/\/education\.github\.com\/api\/user$ requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/workingcopy.js,script-update-interval=0
# CamScanner
http-response ^https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\? requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/CamScaner.js,script-update-interval=0
# playerxtreme
http-response ^https:\/\/secure\.istreamer\.com\/backend$ requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/playerxtreme.js,script-update-interval=0
# grammarly
http-response ^https:\/\/subscription\.grammarly\.com\/api\/v1$ requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/grammarly.js,script-update-interval=0
