# Camera - Video edit

hostname = bmall.camera360.com, vsco.co, viva-asia1.vvbrd.com, api.picsart.com, owa.videoshowiosglobalserver.com:0, api-intl.mr.meitu.com, ap*.intsig.net, *.videostarapp.com, lcs-mobile-cops.adobe.io, 

# camera360
^https:\/\/bmall\.camera360\.com\/api\/(iap\/check-receipt$|mix\/getinfo$) url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/camera360.vip.js

# vsco
^https?:\/\/vsco\.co\/api\/subscriptions\/2.1\/user-subscriptions\/ url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/vsco.js

# Vivavideo
^https:\/\/viva-asia1\.vvbrd\.com\/api\/rest\/u\/vip* url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/vivavideo.vip.js

# PicsArt
^https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/picsArt.vip.js

# Videoshow
^https:\/\/owa\.videoshowiosglobalserver\.com\/.*\/iosPayClient url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/videoshow.vip.js

# beautyplus
^https:\/\/api-intl\.mr\.meitu\.com/.*/subs_offer_elg$ url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/beautyplusvip.js

# CamScanner
^https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\? url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/CamScaner.js

# VideoStar
^https?:\/\/.*\.videostarapp\.com\/scripts\/subsNew\.php url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/VideoStar.js

# phothop & PSexpress
^https:\/\/lcs-mobile-cops\.adobe\.io\/mobile_profile url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/photoshop.js
