# Audio - Video

hostname = api.tv.zing.vn, api.global.mp3.zing.vn, *.fluids.com, apic.musixmatch.com, ios.prod.ftl.netflix.com, 

# Youtube
^https://[\s\S]*\.googlevideo\.com/.*&(oad|ctier) url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/youtube.surge.js

# Nhaccuatui
^https:\/\/graph\.nhaccuatui\.com\/.*\/users\/info* url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/nhaccuatui.js

# zingtv
^https?:\/\/api\.tv\.zing\.vn\/.*/user* url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/zingtvvipv1.js

# zingmp3
^https:\/\/api\.global\.mp3\.zing\.vn\/1\.0\/getUserInfo\?data=* url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/zingmp3.js
^https:\/\/api\.global\.mp3\.zing\.vn\/1\.0\/getDownloadSongInfo\?data url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/zingmp3.downloadsong.js
^https:\/\/api\.global\.mp3\.zing\.vn\/1\.0\/getSongInfo\?data url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/zingmp3.getsong.js

# Phim tài liệu (fuliapps.com)
^https?:\/\/(ios|apple)\.fuliapps\.com\/ url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/PhimTaiLieu.js

# Musixmatch
^https:\/\/apic\.musixmatch\.com\/ws\/.*\/config\.get url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/musixmatch.miao.js

# playerxtreme
^https:\/\/secure\.istreamer\.com\/backend$ url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/playerxtreme.js

#Netflix
^https?://ios\.prod\.ftl\.netflix\.com/iosui/user/.+path=%5B%22videos%22%2C%\d+%22%2C%22summary%22%5D url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/Netflix.js
^https?://ios\.prod\.ftl\.netflix\.com/iosui/user/.+path=%5B%22videos%22%2C%\d+%22%2C%22summary%22%5D url script-request-header https://raw.githubusercontent.com/khitamdao/MinhNT/Script/DichVuTrucTuyen/Netflix.js
