# document

hostname = photos.adobe.io, license.pdfexpert.com, api.lingokids.com, duolingo-leaderboards-prod.duolingo.com, receipt-validator.herewetest.com, license.pdfexpert.com, ssl-api.itranslateapp.com, education.github.com, ap*.intsig.net, secure.istreamer.com, subscription.grammarly.com, 

# lightroom
^https:\/\/photos\.adobe\.io\/v2\/accounts* url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/Lightroom.js

# Pdfexpert
^https:\/\/license\.pdfexpert\.com\/api\/1\.0\/pdfexpert6\/subscription\/(refresh$|check$) url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/Pdfexpert.vip.js

# lingokids
^https:\/\/api\.lingokids\.com\/v1\/renovate_session$ url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/lingokids.vip.js

# duolingo
^https:\/\/duolingo-leaderboards-prod\.duolingo\.com\/leaderboards* url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/duolingo.js

# speak & translate
^https:\/\/receipt-validator\.herewetest\.com\/apple\/verifyTransaction$ url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/speak&translate.js

# document
^https:\/\/license\.pdfexpert\.com\/api\/.*\/https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents//subscription\/(refresh$|check$) url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/documents.js

# itranslate
^https:\/\/ssl-api\.itranslateapp\.com\/.*\/subscriptions\/.*\/ios$ url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/itranslate.js

# workingcopy
^https:\/\/education\.github\.com\/api\/user$ url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Documents/workingcopy.js

# CamScanner
^https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\? url script-response-body https://raw.githubusercontent.com/khitamdao/MinhNT/Script/Anh_Video/CamScaner.js

# playerxtreme
^https:\/\/secure\.istreamer\.com\/backend$ url script-response-body https://raw.githubusercontent.com/khitamdao/script/master/playerxtreme.js

#grammarly
^https:\/\/subscription\.grammarly\.com\/api\/v1$ url script-response-body https://raw.githubusercontent.com/khitamdao/script/master/grammarly.js
